name: Autoassign issues
on:
  issues:
    types: [opened]
jobs:
  assignMonaLisa:
    name: Assign owner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Assign RF5
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign @RF5
